core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracer.urls', namespace='tracer')),
]

tracer/urls.py
from django.urls import path, re_path
from django.urls.conf import include

from .views import (account, home, project, wiki,
                    file, setting, issues, dashboard,statistics)

app_name = 'tracer'

urlpatterns = [
    path('register/', account.register, name='register'),
    path('login/sms/', account.login_sms, name='login_sms'),
    path('login/', account.login, name='login'),
    path('logout/', account.logout, name='logout'),
    path('image/code/', account.image_code, name='image_code'),
    path('send/sms/', account.send_sms, name='send_sms'),
    path('', home.index, name='index'),
    path('index/', home.index, name='index'),


    path('price/', home.price, name='price'),
    re_path('payment/(?P<policy_id>\d+)/$', home.payment, name='payment'),
    path('pay/', home.pay, name='pay'),
    path('pay/notify/', home.pay_notify, name='pay_notify'),

    # project list
    path('project/list/', project.project_list, name='project_list'),
    re_path('project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    re_path('project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar,
            name='project_unstar'),

    # project manage
    re_path('manage/(?P<project_id>\d+)/', include([
        re_path('dashboard/$', dashboard.dashboard, name='dashboard'),
        re_path('dashboard/issues/chart/$', dashboard.issues_chart, name='issues_chart'),

        re_path('statistics/$', statistics.statistics, name='statistics'),
        re_path('statistics/priority/$', statistics.statistics_priority, name='statistics_priority'),
        re_path('statistics/project/user$', statistics.statistics_project_user, name='statistics_project_user'),

        re_path('wiki/$', wiki.wiki, name='wiki'),
        re_path('wiki/add/$', wiki.wiki_add, name='wiki_add'),
        re_path('wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),
        re_path('wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),
        re_path('wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        re_path('wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),  # upload image to wiki

        re_path('file/$', file.file, name='file'),
        re_path('file/delete/$', file.file_delete, name='file_delete'),
        re_path('cos/cos_credentials/$', file.cos_credentials, name='cos_credentials'),
        re_path('file/post/$', file.file_post, name='file_post'),  # upload file name and size to database
        re_path('file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),

        re_path('setting/$', setting.setting, name='setting'),
        re_path('setting/delete/$', setting.setting_delete, name='setting_delete'),
        re_path('setting/change/password/$', setting.change_password, name='change_password'),


        re_path('issues/$', issues.issues, name='issues'),
        re_path('issues/detail/(?P<issue_id>\d+)/$', issues.issues_detail, name='issues_detail'),
        re_path('issues/record/(?P<issue_id>\d+)/$', issues.issues_record, name='issues_record'),
        re_path('issues/change/(?P<issue_id>\d+)/$', issues.issues_change, name='issues_change'),
        re_path('issues/invite/url/$', issues.invite_url, name='invite_url'),
    ])),
    re_path('invite/join/(?P<code>\w+)/$', issues.invite_join, name='invite_join'),
]

tracer/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    username = models.CharField(verbose_name='Username', max_length=100, unique=True, db_index=True)
    email = models.EmailField(verbose_name='Email',
                              unique=True, max_length=100, db_index=True)
    mobile_phone = models.CharField(
        verbose_name='MobilePhone', max_length=17, db_index=True)
    # mobile_phone = PhoneNumberField(null=False, blank=False, unique=True)
    password = models.CharField(verbose_name='Password', max_length=100)

    def __str__(self):
        return self.username


class PricePolicy(models.Model):
    category_choices = (
        (1, 'Free'),
        (2, 'Pay'),
        (3, 'Other')
    )
    category = models.SmallIntegerField(verbose_name='Pay Type', default=1, choices=category_choices)
    title = models.CharField(verbose_name='Title', max_length=32)
    price = models.PositiveIntegerField(verbose_name='Price')

    project_num = models.PositiveIntegerField(verbose_name='Project Number')
    project_member = models.PositiveIntegerField(verbose_name='Project Member')
    project_space = models.PositiveIntegerField(verbose_name='Single Project Space (GB)')
    per_file_size = models.PositiveIntegerField(verbose_name='Per File Size (MB)')

    create_datetime = models.DateTimeField(verbose_name='Create Datetime', auto_now_add=True)


class Transaction(models.Model):
    status_choices = (
        (1, 'Unpaid'),
        (2, 'Paid'),
    )

    status = models.SmallIntegerField(verbose_name='Status', choices=status_choices)

    order = models.CharField(verbose_name='Order Number', max_length=64, unique=True)
    user = models.ForeignKey(to='UserInfo', verbose_name='User', on_delete=models.CASCADE)
    price_policy = models.ForeignKey(to='PricePolicy', verbose_name='Price Policy', on_delete=models.CASCADE)

    count = models.IntegerField(verbose_name='Count (Year)', help_text='Zero means forever')

    price = models.IntegerField(verbose_name='Actually Paid Price')

    start_datetime = models.DateTimeField(verbose_name='Start Datetime', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='End Datetime', null=True, blank=True)

    create_datetime = models.DateTimeField(verbose_name='Create Datetime', auto_now_add=True)


class Project(models.Model):
    COLOR_CHOICES = (
        (1, '#56b8eb'),
        (2, '#f28033'),
        (3, '#ebc656'),
        (4, '#a2d148'),
        (5, '#20BFA4'),
        (6, '#7461c2'),
        (7, '#20bfa3'),
        (8, '#f6a739'),
        (9, '#F538A9'),
        (10, '#A5D6A7'),
    )

    name = models.CharField(verbose_name='Name', max_length=128)
    color = models.SmallIntegerField(verbose_name='Color', default=1, choices=COLOR_CHOICES)
    description = models.CharField(verbose_name='Description', max_length=255, null=True, blank=True)
    use_space = models.BigIntegerField(
        verbose_name='Used Space (Bytes)', default=0, help_text='Bytes')
    star = models.BooleanField(verbose_name='Star', default=False)

    bucket = models.CharField(verbose_name='COS Bucket Name', max_length=128)  # tencent cos cloud storage bucket name
    region = models.CharField(verbose_name='COS Region', max_length=32)  # tencent cos cloud storage region

    join_count = models.IntegerField(verbose_name='Join Member Count', default=1)
    creator = models.ForeignKey(to='UserInfo', verbose_name='Creator', on_delete=models.CASCADE)
    create_datetime = models.DateTimeField(verbose_name='Create Datetime', auto_now_add=True)


class ProjectUser(models.Model):
    """Project member"""
    user = models.ForeignKey(to='UserInfo', verbose_name='User', on_delete=models.CASCADE, related_name='projects')
    project = models.ForeignKey(to='Project', verbose_name='Project', on_delete=models.CASCADE)

    # invitee = models.ForeignKey(to='UserInfo', verbose_name='Invitee', on_delete=models.CASCADE, null=True, blank=True,
    #                             related_name='invitees')

    star = models.BooleanField(verbose_name='Star', default=False)

    create_datetime = models.DateTimeField(verbose_name='Join Datetime', auto_now_add=True)


class Wiki(models.Model):
    project = models.ForeignKey(to='Project', verbose_name='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Title', max_length=128)
    content = models.TextField(verbose_name='Content')
    # content = MDTextField(verbose_name='Content')
    # create_datetime = models.DateTimeField(verbose_name='Create Datetime', auto_now_add=True)

    depth = models.IntegerField(verbose_name='Depth', default=1)

    # 子关联
    parent = models.ForeignKey(to='self', verbose_name='Parent Article',
                               on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self):
        return self.title


class File(models.Model):
    """File system"""
    file_type_choices = (
        (1, 'File'),
        (2, 'Folder'),
    )
    project = models.ForeignKey(to='Project', verbose_name='Project', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Name', max_length=128, help_text='File/Folder name')
    file_type = models.SmallIntegerField(verbose_name='Type', choices=file_type_choices)  # 1: file, 2: folder
    file_size = models.BigIntegerField(verbose_name='Size', null=True, blank=True, help_text='bytes')
    file_path = models.CharField(verbose_name='File Path', max_length=255, null=True,
                                 blank=True)  # the location of the file on the tencent cos server
    parent = models.ForeignKey(to='self', verbose_name='Parent Folder', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='children')
    key = models.CharField(verbose_name='cos key', max_length=128, null=True, blank=True)  # the name stored in cos
    update_user = models.ForeignKey(to='UserInfo', verbose_name='Update User', on_delete=models.CASCADE)
    update_datetime = models.DateTimeField(verbose_name='Update Datetime', auto_now=True)


class Issues(models.Model):
    """Issues"""
    project = models.ForeignKey(to='Project', verbose_name='Project', on_delete=models.CASCADE)
    issues_type = models.ForeignKey(to='IssuesType', verbose_name='Issues type', on_delete=models.CASCADE)
    module = models.ForeignKey(to='Module', verbose_name='Module', on_delete=models.CASCADE, null=True, blank=True)

    subject = models.CharField(verbose_name='Subject', max_length=128)
    desc = models.TextField(verbose_name='Description', null=True, blank=True)

    priority_choices = (
        ("danger", "High"),
        ("warning", "Middle"),
        ("success", "Low"),
    )
    priority = models.CharField(verbose_name='Priority', max_length=16, choices=priority_choices, default='danger')

    # 新建，处理中，已解决，已忽略，待反馈，已关闭，重新打开
    status_choices = (
        (1, 'New'),
        (2, 'Processing'),
        (3, 'Solved'),
        (4, 'Ignored'),
        (5, 'Feedback'),
        (6, 'Closed'),
        (7, 'Reopened'),
    )
    status = models.SmallIntegerField(verbose_name='Status', choices=status_choices, default=1)

    assign = models.ForeignKey(to='UserInfo', verbose_name='Assign to', on_delete=models.CASCADE, related_name='task',
                               null=True, blank=True)

    attention = models.ManyToManyField(to='UserInfo', verbose_name='Attention', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='Start Date', null=True, blank=True)
    end_date = models.DateField(verbose_name='End Date', null=True, blank=True)

    mode_choices = (
        (1, 'Public Mode'),
        (2, 'Private Mode'),
    )
    mode = models.SmallIntegerField(verbose_name='Mode', choices=mode_choices, default=1)

    parent = models.ForeignKey(to='self', verbose_name='Parent Issue', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='children')

    creator = models.ForeignKey(to='UserInfo', verbose_name='Creator', on_delete=models.CASCADE,
                                related_name='create_problems')
    create_datetime = models.DateTimeField(verbose_name='Create Datetime', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='Latest Update Datetime', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """Module (Milestone) for issue tracking"""
    project = models.ForeignKey(to='Project', verbose_name='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Title', max_length=128)

    def __str__(self):
        return self.title


class IssuesType(models.Model):
    """Issues type, such as Bug, Feature, Task, etc."""

    PROJECT_INIT_LIST = ['Task', 'Bug', 'Feature']

    project = models.ForeignKey(to='Project', verbose_name='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Title', max_length=128)

    def __str__(self):
        return self.title


class IssuesReply(models.Model):
    """The model of issues reply system"""

    reply_type_choices = (
        (1, 'Edit Comment'),
        (2, 'Comment'),
    )

    reply_type = models.SmallIntegerField(verbose_name='Reply Type', choices=reply_type_choices)
    issues = models.ForeignKey(to='Issues', verbose_name='Issues', on_delete=models.CASCADE)
    content = models.TextField(verbose_name='Content')
    creator = models.ForeignKey(to='UserInfo', verbose_name='Creator', on_delete=models.CASCADE)
    create_datetime = models.DateTimeField(verbose_name='Create Datetime', auto_now_add=True)
    reply = models.ForeignKey(to='self', verbose_name='Reply', on_delete=models.CASCADE, null=True, blank=True)


class ProjectInvite(models.Model):
    """Project invite"""
    project = models.ForeignKey(to='Project', verbose_name='Project', on_delete=models.CASCADE)

tracer/forms/widgets.py
from django.forms import RadioSelect


class ColorRadioSelect(RadioSelect):
    template_name = 'widgets/color_radio/radio.html'
    option_template_name = 'widgets/color_radio/radio_option.html'

tracer/views/account.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from tracer import models
from tracer.forms.account import LoginForm, RegisterForm, SendSmsForm, LoginSmsForm
from utils.image_code import generate_image_code
from io import BytesIO
import uuid
import datetime

def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})
    
    form = RegisterForm(data=request.POST)
    if form.is_valid():
        instance = form.save()
        """
        policy_object = models.PricePolicy.objects.filter(
            category=1, title='Personal Free').first()
        """
        policy_object=models.PricePolicy.objects.create(
            category=1,
            title="Personal Free",
            price=0,
            project_num=3,
            project_member=2,
            project_space=20,
            per_file_size=5
        )
        # 创建默认交易记录，当创建用户时自动创建
        models.Transaction.objects.create(
            status=2,
            order=str(uuid.uuid4()),
            user=instance, 
            price_policy=policy_object,
            count = 0,
            price = 0,
            start_datetime = datetime.datetime.now()
        )
        return JsonResponse({'status': True, 'data': '/login/'})
    
    return JsonResponse({'status': False, 'errors': form.errors})

def send_sms(request):
    """
    Send sms
    """
    form = SendSmsForm(request, data=request.GET)
    if form.is_valid():
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'errors': form.errors})

def login_sms(request):
    """
    Login with sms
    """
    if request.method == 'GET':
        form = LoginSmsForm()
        return render(request, 'login_sms.html', {'form': form})
    
    form = LoginSmsForm(data=request.POST)
    if form.is_valid():
        mobile_phone = form.cleaned_data['mobile_phone']
        
        # write the user name into session
        user_object = models.UserInfo.objects.filter(mobile_phone=mobile_phone).first()
        request.session['user_id'] = user_object.id
        request.session.set_expiry(60 * 60 * 24 * 14)
        # return redirect('tracer:index')
        return JsonResponse({'status': True, 'data': '/index/'})
    
    return JsonResponse({'status': False, 'errors': form.errors})

def login(request):
    """use username and password"""
    
    if request.method == 'GET':
        form = LoginForm(request)
        return render(request, 'login.html', {'form': form})
    
    form = LoginForm(request, data=request.POST)
    if form.is_valid():
        email_or_phone = form.cleaned_data['email_or_phone']
        password = form.cleaned_data['password']
        
        from django.db.models import Q
        user_object = models.UserInfo.objects.filter(Q(mobile_phone=email_or_phone) | Q(email=email_or_phone)).filter(password=password).first()
        
        if user_object:
            request.session['user_id'] = user_object.id
            request.session.set_expiry(60 * 60 * 24 * 14)
            return redirect('tracer:index')
        form.add_error('email_or_phone', 'Invalid username or password')

    return render(request, 'login.html', {'form': form})

def image_code(request):
    """
    generate the url for image code
    """

    image_object, code = generate_image_code()
    # save image code to session
    request.session['image_code'] = code
    # set expired time to 60a
    request.session.set_expiry(60)
    
    stream = BytesIO()
    image_object.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    """
    logout
    """
    request.session.flush()
    return redirect('tracer:index')

tracer/templates/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} User Sms login {% endblock title %}

{% block css %}
 
    {% comment %} <link rel="stylesheet" href="{% static 'css/account.css' %}"> {% endcomment %}
    <style>
        .error-msg {
            color:red;
            position: absolute;
            font-size: 12px;
        }
    </style>
{% endblock css %}

{% block content %}
<section class="vh-100">
  <div class="container h-100">
    <div class="row d-flex align-items-center justify-content-center h-75">
        
      <div class="col-md-8 col-lg-7 col-xl-6">
        <img src="{% static 'img/sms_login.svg' %}" class="img-fluid" alt="Phone image">
      </div>
      
      <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
        <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-3">Login with SMS</p>
        <form id="form" class="mx-1 mx-md-4" method="POST" novalidate>
            {% csrf_token %}
            <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="form3Example4cd">Mobile phone</label>
                        {{ form.mobile_phone }}
                        <span class="error-msg"></span>
                    </div>
                  </div>

                   <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for="form3Example4cd">Verification code</label>
                            <div class="row">
                            <div class="col">
                                {{ form.code }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-auto">
                                <input id="btnSms" type="button" class="btn btn-outline-primary" value="Verify Code">
                            </div>
                        </div>
                    </div>
                  </div>

          <!-- Submit button -->
          <div class="text-center text-lg-start mt-4 pt-2">
   
            <button id="btnSubmit" type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
            <div class="row align-items-end">
                  <div class="col">
                  <p class="middle fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'tracer:register' %}"
                class="link-info">Register</a></p>
                  </div>
                  <div class="col-auto">
            <a href="{% url 'tracer:login' %}"
                class="link-primary">Email or Mobilephone Login</a>
                </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<{% endblock content %}
{% block js %}
    <script>
        // 页面框架加载完成之后自动执行的js代码
        $(function() {
            bindClickBtnSms();
            bindClickBtnSubmit();
        });

        function bindClickBtnSms() {
            $('#btnSms').click(function() {

                // 清除错误提示
                $('.error-msg').empty();

                var mobilePhone = $('#id_mobile_phone').val();

                // 发送ajax请求
                $.ajax({
                    url: "{% url 'tracer:send_sms' %}",
                    type: 'GET',
                    data: {
                        mobile_phone: mobilePhone, tpl: "login"
                    },
                    dataType: 'JSON',
                    success: function(res) {
                        if(res.status){
                            sendSmsRemind(60);
                        }else{
                            $.each(res.errors, function(key, value) {
                                $('#id_' + key).next().text(value[0]);
                            });
                        }
                    }
                });
            })
        }

        // 发送短信验证码
        function sendSmsRemind(time) {
            var $smsBtn = $('#btnSms');
            $smsBtn.attr('disabled', true);
            $smsBtn.val(time + 's resend');
            var timer = setInterval(function() {
                time--;
                $smsBtn.val(time + 's resend');
                if(time <= 0) {
                    clearInterval(timer);
                    $smsBtn.attr('disabled', false);
                    $smsBtn.val('Verify Code');
                }
            }, 1000);
        }

        // 点击提交按钮
        function bindClickBtnSubmit() {
            $('#btnSubmit').click(function() {
                // 清除错误提示
                $('.error-msg').empty();

                // 包含所有form表单的数据和csrf_token
                var formData = $('#form').serialize();

                // 发送ajax请求
                $.ajax({
                    url: "{% url 'tracer:login_sms' %}",
                    type: 'POST',
                    data: formData,
                    dataType: 'JSON',
                    success: function(res) {
                        if(res.status){
                            location.href = res.data;
                        }else{
                            $.each(res.errors, function(key, value) {
                                $('#id_' + key).next().text(value[0]);
                            });
                        }
                    }
                }); 
            })
        }
    </script>
{% endblock js %}	

tracer/templates/payment_success.html
{% extends 'layout/manage.html' %}
{% load static %}

{% block title %}Payment Successful{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
    <img src="{% static 'img/payment_success.png' %}" alt="Success" class="img-responsive" style="margin: 0 auto;">
{% endblock %}

tracer/templates/project_list.html
{% extends 'layout/manage.html' %} {% block css %}
<style>

  .project {
    margin-top: 2rem;
  }

  .card {
    margin-bottom: 1rem;
  }

  .card-body {
    padding: 0;
    display: flex;
    flex-direction: row;
    justify-content: left;
    align-items: flex-start;
    flex-wrap: wrap;
  }

  .card-body > .item {
    border-radius: 6px;
    width: 228px;
    border: 1px solid #dddddd;
    margin: 20px 10px;
  }
  .card-body > .item:hover {
    border: 1px solid #f0ad4e;
  }
  .card-body > .item > .title {
    height: 104px;
    color: white;
    display: flex;
    justify-content: center;
    align-items: center;
    border-top-left-radius: 6px;
    border-top-right-radius: 6px;
    font-size: 20px;
    text-decoration: none;
  }
  .card-body > .item > .info {
    padding: 10px 10px;
    display: flex;
    justify-content: space-between;
    border-bottom-left-radius: 6px;
    border-bottom-right-radius: 6px;
    color: #8c8c8c;
  }
  .card-body > .item > .info a {
    text-decoration: none;
  }
  .card-body > .item > .info .fa-star {
    font-size: 18px;
  }

  .color-radio label {
      margin-left: 0;
      padding-left: 0;
  }
  .color-radio input[type="radio"] {
    display: none;
    }
    
    .color-radio input[type="radio"] + .circle {
        display: inline-block;
        height: 25px;
        width: 25px;
        border-radius: 50%;
        border: 2px solid #dddddd;
    }
    .color-radio input[type="radio"]:checked + .circle {
      border: 2px solid #3f3f3f;
    }
  .error-msg {
              color:red;
              position: absolute;
              font-size: 12px;
          }
</style>
{% endblock css %}
{% block title %}Project List{% endblock %}

{% block content %}
<div class="container-fluid project">
  <div style="margin: 20px 0">
    <a
      class="btn btn-outline-primary btn-lg"
      data-bs-toggle="modal"
      data-bs-target="#modal"
      ><i class="fas fa-plus-circle"></i> New Project</a
    >
  </div>
  <div class="card">
    <div class="card-header"><i class="fas fa-star"></i> Stared Projects</div>
    <div class="card-body">
      {% for item in project_dict.star_project %}
      <div class="item">
        <a
          href="{% url 'tracer:dashboard' project_id=item.value.id %}"
          class="title"
          style="background-color:{{item.value.get_color_display}}"
          >{{item.value.name}}</a>

        <div class="info">
          <div>
            <a href="{% url 'tracer:project_unstar' project_type=item.type project_id=item.value.id %}">
              <i
                class="fas fa-star"
                aria-hidden="true"
                style="color: #f0ad4e"
              ></i>
            </a>
            <span> {{item.value.creator.username}} </span>
          </div>
          <div>
            <i class="far fa-user" aria-hidden="true"></i>
            <span> {{ item.value.join_count }} </span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="card">
    <div class="card-header"><i class="fas fa-list"></i> My Projects</div>
    <div class="card-body">
      {% for item in project_dict.my_project %}
      <div class="item">
        <a
          href="{% url 'tracer:dashboard' project_id=item.id %}"
          class="title"
          style="background-color:{{item.get_color_display}}"
          >{{item.name}}</a
        >

        <div class="info">
          <div>
            <a href="{% url 'tracer:project_star' project_type='my_project' project_id=item.id %}">
              <i
                class="fas fa-star"
                aria-hidden="true"
                style="color: #d5d5d5"
              ></i>
            </a>
            <span> {{item.creator.username}} </span>
          </div>
          <div>
            <i class="far fa-user" aria-hidden="true"></i>
            <span>{{item.join_count}}</span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <i class="far fa-handshake"></i> Joined Projects
    </div>
    <div class="card-body">
      {% for item in project_dict.join_project %}
      <div class="item">
        <a
          href="{% url 'tracer:dashboard' project_id=item.id %}"
          class="title"
          style="background-color:{{item.get_color_display}}"
          >{{item.name}}</a
        >

        <div class="info">
          <div>
            <a href="{% url 'tracer:project_star' project_type='join_project' project_id=item.id %}">
              <i
                class="fas fa-star"
                aria-hidden="true"
                style="color: #d5d5d5"
              ></i>
            </a>
            <span> {{item.creator.username}} </span>
          </div>
          <div>
            <i class="far fa-user" aria-hidden="true"></i>
            <span>{{item.join_count}}</span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<!-- Modal -->
<div
  class="modal fade"
  id="modal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create A New Project</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form id="addForm">
          {% csrf_token %} {% for field in form %}
          <div class="mb-3">
            <label for="{{field.id_for_label }}" class="form-label fw-bold"
              >{{ field.label }}</label
            >
            {{ field }}
            <span class="error-msg"></span>
          </div>
          {% endfor %}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cancel
        </button>
        <button id="btnSubmit" type="button" class="btn btn-primary">
          Save
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock content %} 
{% block js %}
<script>
  $(function () {
    bindSubmit();
  });

  function bindSubmit() {
    $("#btnSubmit").click(function () {
      $.ajax({
        url: "{% url 'tracer:project_list' %}",
        type: "POST",
        data: $("#addForm").serialize(),
        dataType: "JSON",
        success: function (res) {
          if (res.status) {
            location.href = location.href;
          } else {
            $.each(res.errors, function (key, value) {
              $("#id_" + key)
                .next()
                .text(value[0]);
            });
          }
        },
      });
    });
  }
</script>
{% endblock js %}

tracer/templates/setting.html
{% extends 'layout/manage.html' %}

{% block css %}
<style>
        .card {
            margin-top: 2rem;
        }
</style>

{% endblock css %}

{% block content %}
  <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3">
            <div class="card">
                <div class="card-header" style="background-color:transparent; font-weight:500"> 
                    Personal Center
                </div>
                
                    <div class="list-group" style="border-radius:0">
                        <a class="list-group-item list-group-item-action" href="#">My Profile</a>
                        <a class="list-group-item list-group-item-action" href="{% url 'tracer:change_password' project_id=request.tracer.project.id %}">Change Password</a>
                        <a class="list-group-item list-group-item-action" href="{% url 'tracer:setting_delete' project_id=request.tracer.project.id %}">Delete Project</a>
                    </div>
                 
                </div>
            </div>
        <div class="col-sm-9">
            <div class="card">
                <div class="card-header">
                    <div>
                        <i class="far fa-id-card"></i> My Profile
                    </div>
                </div>
                <div class="card-body">System Settings</div>
            </div>
        </div>

    </div>
  </div>
{% endblock content %}