core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracer.urls', namespace='tracer')),
]

tracer/urls.py
from django.urls import path, re_path
from django.urls.conf import include

from .views import (account, home, project, wiki,
                    file, setting, issues, dashboard,statistics)

app_name = 'tracer'

urlpatterns = [
    path('register/', account.register, name='register'),
    path('login/sms/', account.login_sms, name='login_sms'),
    path('login/', account.login, name='login'),
    path('logout/', account.logout, name='logout'),
    path('image/code/', account.image_code, name='image_code'),
    path('send/sms/', account.send_sms, name='send_sms'),
    path('', home.index, name='index'),
    path('index/', home.index, name='index'),


    path('price/', home.price, name='price'),
    re_path('payment/(?P<policy_id>\d+)/$', home.payment, name='payment'),
    path('pay/', home.pay, name='pay'),
    path('pay/notify/', home.pay_notify, name='pay_notify'),

    # project list
    path('project/list/', project.project_list, name='project_list'),
    re_path('project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    re_path('project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar,
            name='project_unstar'),

    # project manage
    re_path('manage/(?P<project_id>\d+)/', include([
        re_path('dashboard/$', dashboard.dashboard, name='dashboard'),
        re_path('dashboard/issues/chart/$', dashboard.issues_chart, name='issues_chart'),

        re_path('statistics/$', statistics.statistics, name='statistics'),
        re_path('statistics/priority/$', statistics.statistics_priority, name='statistics_priority'),
        re_path('statistics/project/user$', statistics.statistics_project_user, name='statistics_project_user'),

        re_path('wiki/$', wiki.wiki, name='wiki'),
        re_path('wiki/add/$', wiki.wiki_add, name='wiki_add'),
        re_path('wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),
        re_path('wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),
        re_path('wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        re_path('wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),  # upload image to wiki

        re_path('file/$', file.file, name='file'),
        re_path('file/delete/$', file.file_delete, name='file_delete'),
        re_path('cos/cos_credentials/$', file.cos_credentials, name='cos_credentials'),
        re_path('file/post/$', file.file_post, name='file_post'),  # upload file name and size to database
        re_path('file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),

        re_path('setting/$', setting.setting, name='setting'),
        re_path('setting/delete/$', setting.setting_delete, name='setting_delete'),
        re_path('setting/change/password/$', setting.change_password, name='change_password'),


        re_path('issues/$', issues.issues, name='issues'),
        re_path('issues/detail/(?P<issue_id>\d+)/$', issues.issues_detail, name='issues_detail'),
        re_path('issues/record/(?P<issue_id>\d+)/$', issues.issues_record, name='issues_record'),
        re_path('issues/change/(?P<issue_id>\d+)/$', issues.issues_change, name='issues_change'),
        re_path('issues/invite/url/$', issues.invite_url, name='invite_url'),
    ])),
    re_path('invite/join/(?P<code>\w+)/$', issues.invite_join, name='invite_join'),
]

tracer/forms/bootstrap.py
class BootstrapForm(object):
    
    bootstrap_class_exclude = []
    
    def __init__(self, *args, **kwargs):
        super(BootstrapForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            
            if name in self.bootstrap_class_exclude:
                continue
            
            old_class = field.widget.attrs.get('class',"")
            if old_class and old_class != 'form-control': 
                field.widget.attrs['class'] = '{} form-control'.format(old_class)
            else:
                field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = 'Please enter %s' % (
                field.label,)

tracer/forms/widgets.py
from django.forms import RadioSelect


class ColorRadioSelect(RadioSelect):
    template_name = 'widgets/color_radio/radio.html'
    option_template_name = 'widgets/color_radio/radio_option.html'

tracer/views/account.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from tracer import models
from tracer.forms.account import LoginForm, RegisterForm, SendSmsForm, LoginSmsForm
from utils.image_code import generate_image_code
from io import BytesIO
import uuid
import datetime

def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})
    
    form = RegisterForm(data=request.POST)
    if form.is_valid():
        instance = form.save()
        """
        policy_object = models.PricePolicy.objects.filter(
            category=1, title='Personal Free').first()
        """
        policy_object=models.PricePolicy.objects.create(
            category=1,
            title="Personal Free",
            price=0,
            project_num=3,
            project_member=2,
            project_space=20,
            per_file_size=5
        )
        # 创建默认交易记录，当创建用户时自动创建
        models.Transaction.objects.create(
            status=2,
            order=str(uuid.uuid4()),
            user=instance, 
            price_policy=policy_object,
            count = 0,
            price = 0,
            start_datetime = datetime.datetime.now()
        )
        return JsonResponse({'status': True, 'data': '/login/'})
    
    return JsonResponse({'status': False, 'errors': form.errors})

def send_sms(request):
    """
    Send sms
    """
    form = SendSmsForm(request, data=request.GET)
    if form.is_valid():
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'errors': form.errors})

def login_sms(request):
    """
    Login with sms
    """
    if request.method == 'GET':
        form = LoginSmsForm()
        return render(request, 'login_sms.html', {'form': form})
    
    form = LoginSmsForm(data=request.POST)
    if form.is_valid():
        mobile_phone = form.cleaned_data['mobile_phone']
        
        # write the user name into session
        user_object = models.UserInfo.objects.filter(mobile_phone=mobile_phone).first()
        request.session['user_id'] = user_object.id
        request.session.set_expiry(60 * 60 * 24 * 14)
        # return redirect('tracer:index')
        return JsonResponse({'status': True, 'data': '/index/'})
    
    return JsonResponse({'status': False, 'errors': form.errors})

def login(request):
    """use username and password"""
    
    if request.method == 'GET':
        form = LoginForm(request)
        return render(request, 'login.html', {'form': form})
    
    form = LoginForm(request, data=request.POST)
    if form.is_valid():
        email_or_phone = form.cleaned_data['email_or_phone']
        password = form.cleaned_data['password']
        
        from django.db.models import Q
        user_object = models.UserInfo.objects.filter(Q(mobile_phone=email_or_phone) | Q(email=email_or_phone)).filter(password=password).first()
        
        if user_object:
            request.session['user_id'] = user_object.id
            request.session.set_expiry(60 * 60 * 24 * 14)
            return redirect('tracer:index')
        form.add_error('email_or_phone', 'Invalid username or password')

    return render(request, 'login.html', {'form': form})

def image_code(request):
    """
    generate the url for image code
    """

    image_object, code = generate_image_code()
    # save image code to session
    request.session['image_code'] = code
    # set expired time to 60a
    request.session.set_expiry(60)
    
    stream = BytesIO()
    image_object.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    """
    logout
    """
    request.session.flush()
    return redirect('tracer:index')

tracer/views/dashboard.py
import collections
import datetime
import time

from django.shortcuts import render
from tracer import models
from django.db.models import Count
from django.http import JsonResponse


def dashboard(request, project_id):
    # issues status
    status_dict = {}
    for key, text in models.Issues.status_choices:
        status_dict[key] = {'text': text, 'count': 0}

    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    for item in issues_data:
        status_dict[item['status']]['count'] = item['ct']

    # project user
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values('user_id', 'user__username')

    # top 10 issues assignee 并且指派者不为空
    top_ten = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by('-id')[:10]
    context = {
        'status_dict': status_dict,
        'user_list': user_list,
        'top_ten': top_ten,
    }
    return render(request, 'dashboard.html', context)


def issues_chart(request, project_id):
    # 最近30天，每天创建的issue数量 & 根据每天的数量分组
    today = datetime.date.today()
    result = models.Issues.objects.filter(project_id=project_id, create_datetime__gte=today - datetime.timedelta(days=30)).extra(
        select={'ctime': "to_char(tracer_issues.create_datetime,'YYYY-MM-DD')"}).values('ctime').annotate(ct=Count('id'))

    # result: <QuerySet [{'ctime': '2022-02-09', 'ct': 1}, {'ctime': '2022-02-08', 'ct': 1}]>
    date_dict = collections.OrderedDict()
    for i in range(30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime('%Y-%m-%d')] = [time.mktime(date.timetuple())*1000, 0]

    for item in result:
        date_dict[item['ctime']][1] = item['ct']
    return JsonResponse({'status': 'true', 'data': list(date_dict.values())})

tracer/views/file.py
import json
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from tracer import models
from tracer.forms.file import FolderModelForm, FileModelForm
from utils.encrypt import bytes_readable
from utils.tencent_cos import create_crendentials, delete_file, delete_file_list
import requests
from django.utils.encoding import escape_uri_path


def file(request, project_id):
    """file list"""

    # 判断是否有上级文件夹
    parent_object = None
    folder_id = request.GET.get('folder', "")  # 如果有，则为文件夹，没有则为文件
    if folder_id.isdecimal():
        parent_object = models.File.objects.filter(id=folder_id, file_type=2,
                                                   project=request.tracer.project).first()

    if request.method == 'GET':

        # 生成table导航条
        breadcrumb_list = []
        parent = parent_object
        while parent:
            breadcrumb_list.insert(0, {'id': parent.id, 'name': parent.name})
            parent = parent.parent

        # 当前目录下所有的文件和文件夹
        queryset = models.File.objects.filter(project=request.tracer.project)

        if parent_object:
            # 进入了某个文件夹
            file_object_list = queryset.filter(parent=parent_object).order_by('-file_type')

        else:
            # 没有进入文件夹
            file_object_list = queryset.filter(parent__isnull=True).order_by('-file_type')

        form = FolderModelForm(request, parent_object)
        context = {
            'form': form,
            'file_object_list': file_object_list,
            'breadcrumb_list': breadcrumb_list,
            'folder_object': parent_object
        }

        return render(request, 'file.html', context)

    """POST: add a new folder and edit folder name"""

    fid = request.POST.get('fid', "")
    edit_object = None
    if fid.isdecimal():
        # 编辑文件夹名称
        edit_object = models.File.objects.filter(id=fid, file_type=2, project=request.tracer.project).first()

    if edit_object:
        form = FolderModelForm(request, parent_object, data=request.POST, instance=edit_object)
    else:
        form = FolderModelForm(request, parent_object, data=request.POST)

    if form.is_valid():
        form.instance.project = request.tracer.project
        form.instance.file_type = 2
        form.instance.update_user = request.tracer.user
        form.instance.parent = parent_object
        form.save()
        return JsonResponse({'status': True})

    return JsonResponse({'status': False, 'errors': form.errors})


def file_delete(request, project_id):
    """delete a file or a folder"""

    fid = request.GET.get('fid', "")
    current_project = request.tracer.project

    # 删除数据库中的文件或文件夹 (级联删除)
    delete_object = models.File.objects.filter(id=fid, project=current_project).first()

    if delete_object.file_type == 1:
        # 删除文件 (数据库文件删除， cos文件删除， 当前项目已使用的空间容量要重置)
        current_project.use_space -= delete_object.file_size
        current_project.save()

        # delete cos file
        delete_file(current_project.bucket, delete_object.key)

        # delete database file
        delete_object.delete()

        return JsonResponse({'status': True})

    # else:
    #     # 删除文件夹 (打到该文件夹下所有的文件， 删除， cos文件删除， 当前项目已使用的空间容量要重置)
    #     pass

    else:
        total_size = 0
        key_list = []  # 要删除的cos文件的key列表

        folder_list = [delete_object, ]
        for folder in folder_list:
            child_list = models.File.objects.filter(parent=folder, project=current_project).order_by('-file_type')

            for child in child_list:
                if child.file_type == 2:
                    folder_list.append(child)
                else:
                    # 文件大小汇总
                    total_size += child.file_size

                    # 删除cos文件
                    key_list.append({'key': child.key})

        # cos 批量删除文件
        if key_list:
            delete_file_list(current_project.bucket, key_list)

        # 更新数据库
        if total_size:
            current_project.use_space -= total_size
            current_project.save()

        # 删除数据库文件
        delete_object.delete()
        return JsonResponse({'status': True})


@csrf_exempt
def cos_credentials(request, project_id):
    """获取tencent cos的临时凭证"""
    # 做容量限制: 单个文件 和 项目总容量
    per_file_limit = request.tracer.price_policy.per_file_size  # in MB
    project_space = request.tracer.price_policy.project_space

    # used project space
    used_project_space = request.tracer.project.use_space

    per_file_limit_byte = per_file_limit * 1024 * 1024  # in Byte
    total_file_limit_byte = project_space * 1024 * 1024 * 1024  # in Byte

    file_list = json.loads(request.body.decode('utf-8'))

    total_size = 0

    for item in file_list:
        if item['size'] > per_file_limit_byte:
            msg = f"Single file size cannot exceed {per_file_limit} MB, File name: {item['name']}, Please upgrade your plan"
            return JsonResponse({'status': False, 'error': msg})

        total_size += item['size']

    # 判断总容量是否超过限制
    if used_project_space + total_size > total_file_limit_byte:
        return JsonResponse({'status': False, 'error': 'Project used space exceeded, Please upgrade your plan'})

    response = create_crendentials(request.tracer.project.bucket)
    return JsonResponse({'status': True, 'data': response})


@csrf_exempt  # ajax post cors request
def file_post(request, project_id):
    """将已经上传的文件信息写入数据库
    
    name: fileName,
    key: key,
    file_size: fileSize,
    parent: CURRENT_FOLDER_ID,
    etag: data.ETag,
    file_path: data.Location,
    """

    form = FileModelForm(request, data=request.POST)

    if form.is_valid():
        data_dict = form.cleaned_data
        data_dict.pop('etag')
        data_dict.update(
            {'project': request.tracer.project, 'file_type': 1, 'update_user': request.tracer.user})

        instance = models.File.objects.create(**data_dict)
        # file_size_readable = bytes_readable(instance.file_size)

        # 更新项目已使用空间
        request.tracer.project.use_space += instance.file_size
        request.tracer.project.save()

        result = {
            'id': instance.id,
            'name': instance.name,
            'file_size': instance.file_size,
            'username': instance.update_user.username,
            'datetime': instance.update_datetime.strftime('%Y-%m-%d %H:%M:%S'),
            'download_url': reverse('tracer:file_download', kwargs={'project_id': project_id, 'file_id': instance.id}),
            # 'file_type': instance.get_file_type_display(),
        }
        return JsonResponse({'status': True, 'data': result})

    return JsonResponse({'status': False, 'errors': form.errors})


def file_download(request, project_id, file_id):
    # 找到要下载的文件
    file_object = models.File.objects.filter(id=file_id, project=request.tracer.project).first()

    res = requests.get(file_object.file_path)

    # 文件分块下载
    data = res.iter_content()

    # 设置content-type=application/octet-stream 用于提示下载框
    response = HttpResponse(data, content_type='application/octet-stream')

    # 设置响应头，用于中文文件名转义
    response['Content-Disposition'] = f'attachment; filename={escape_uri_path(file_object.name)}'

    return response

tracer/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/flamingo.png' %}">

    <link
      rel="stylesheet"
      href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugin/fontawesome-6/css/fontawesome.min.css' %}"
    />
     <link rel="stylesheet" href="{% static 'plugin/fontawesome-6/css/all.min.css' %}">

    {% block css %}
    {% endblock css %}
  </head>
  <body>
    <!--navbar-->
    {% include 'layout/navbar.html' %}
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

tracer/templates/layout/manage.html
{% load static %}
{% load project %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/flamingo.png' %}">

    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'plugin/fontawesome-6/css/fontawesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'plugin/fontawesome-6/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/manage.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    {% block css %}
    <style>
        .error-msg {
            color:red;
            position: absolute;
            font-size: 12px;
        }
    </style>
    {% endblock css %}
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid mx-5">
    <a class="navbar-brand" href="{% url 'tracer:index' %}">Tracer</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mb-2 mb-lg-0">

      {% all_project_list request %}
      
      {% if request.tracer.project %}
        {% manage_menu_list request %}
      {% endif %}
      </ul>

      <ul class="navbar-nav ms-auto">
        <li class="nav-item mx-2"><a class="nav-link" href="#">Workspace</a></li>
        <li class="nav-item mx-2"><a class="nav-link" href="#">Calendar</a></li>
        <li class="nav-item mx-2"><a class="nav-link" href="#"><i class="far fa-bell"></i></a></li>
        <li class="nav-item mx-2"><a class="nav-link" href="#"><i class="far fa-question-circle"></i></a></li>

                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{request.tracer.user.username}}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'tracer:index' %}">Homepage</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'tracer:logout' %}">Sign out</a></li>
                </ul>
                </li>
      </ul>
    </div>
  </div>
</nav>
    <div class="container-fluid px-5">
        {% block content %}
        {% endblock content %}
    </div>
    {% block js %}{% endblock js %}
  </body>
</html>

tracer/templates/layout/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'tracer:index' %}">Tracer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">产品功能</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">企业方案</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">帮助文档</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tracer:price' %}">Price</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
      {% if request.tracer.user %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{request.tracer.user.username}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'tracer:project_list' %}">Settings</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{%  url 'tracer:logout' %}">Sign out</a></li>
          </ul>
        </li>
      {% else %}
        <li class="nav-item px-2">
          <a class="btn btn-primary" href="{% url 'tracer:login' %}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-outline-secondary" href="{% url 'tracer:register' %}">Sign Up</a>
        </li>
      {% endif %}


      </ul>
    </div>
  </div>
</nav>